import os
import logging
import json


logger = logging.getLogger(__name__)

# ___ General Configuration ___
LOGGER_NAME = os.getenv("LOGGER_NAME", "podcast_content_monitoring_system")

# ___KAFKA Configuration ___ 
BOOTSTRAP_SERVERS = os.getenv("BOOTSTRAP_SERVERS", "localhost:9092")
KAFKA_TOPIC_FILE_METADATA = os.getenv("KAFKA_TOPIC_FILE_METADATA", "file-metadata")
KAFKA_TOPIC_INCOME_PROCESSING = os.getenv("KAFKA_TOPIC_INCOME_PROCESSING", "icome-processing")
KAFKA_TOPIC_TRANSCRIPTTION = os.getenv("KAFKA_TOPIC_TRANSCRIPTTION", "file-transcribe")
KAFKA_GROUP_ID_FILE_METADATA = os.getenv("KAFKA_GROUP_ID_FILE_METADATA", "information_consumption_processing")
KAFKA_GROUP_ID_INCOME_PROCESSING = os.getenv("KAFKA_GROUP_ID_INCOME_PROCESSING", "icome-processing")
KAFKA_GROUP_ID_TRANSCRIPTTION = os.getenv("KAFKA_GROUP_ID_TRANSCRIPTTION", "file-transcribe")

# ___ ELASTICSEARCH Configuration ___ 
ELASTICSEARCH_HOST = os.getenv("ELASTICSEARCH_HOST", "http://localhost:9200")
ELASTICSEARCH_INDEX_IMAGE_EMBEDDINGS = os.getenv("ELASTICSEARCH_INDEX_IMAGE_EMBEDDINGS", "image_embeddings")
ELASTICSEARCH_INDEX_PERSONS = os.getenv("ELASTICSEARCH_INDEX_PERSONS", "persons")
ELASTICSEARCH_INDEX_LOG = os.getenv("ELASTICSEARCH_INDEX_LOG", "logging")

ELASTICSEARCH_MAPPING_PATH = os.getenv("ELASTICSEARCH_MAPPING_IMAGE_EMBEDDINGS", r"config\elasticsearch_mapping.json")
with open(ELASTICSEARCH_MAPPING_PATH) as f: ELASTICSEARCH_MAPPING_IMAGE_EMBEDDINGS = json.load(f)


logger.info(f"""
            Configuration Loaded ___ :
            LOGGER_NAME: {LOGGER_NAME}
            BOOTSTRAP_SERVERS: {BOOTSTRAP_SERVERS}
            KAFKA_TOPIC_FILE_METADATA: {KAFKA_TOPIC_FILE_METADATA}
            KAFKA_GROUP_ID_FILE_METADATA: {KAFKA_GROUP_ID_FILE_METADATA}
            KAFKA_TOPIC_INCOME_PROCESSING: {KAFKA_TOPIC_INCOME_PROCESSING}
            KAFKA_GROUP_ID_INCOME_PROCESSING: {KAFKA_GROUP_ID_INCOME_PROCESSING}
            KAFKA_TOPIC_TRANSCRIPTTION: {KAFKA_TOPIC_TRANSCRIPTTION}
            KAFKA_GROUP_ID_TRANSCRIPTTION: {KAFKA_GROUP_ID_TRANSCRIPTTION}
            ELASTICSEARCH_HOST: {ELASTICSEARCH_HOST}
            ELASTICSEARCH_INDEX_IMAGE_EMBEDDINGS: {ELASTICSEARCH_INDEX_IMAGE_EMBEDDINGS}
            ELASTICSEARCH_INDEX_PERSONS: {ELASTICSEARCH_INDEX_PERSONS}
            ELASTICSEARCH_INDEX_LOG: {ELASTICSEARCH_INDEX_LOG}
            ELASTICSEARCH_MAPPING_PATH: {ELASTICSEARCH_MAPPING_PATH}
            """)