class VideoFrameExtractorConfig:
    MAX_FRAMES_PER_SECONDS = 2
    MAX_FRAMES_PER_MS = 1000 / MAX_FRAMES_PER_SECONDS
    INTERVAL_SEC = 1 / MAX_FRAMES_PER_SECONDS
    SLIDING_WINDOW_SIZE = 5 #In seconds